# -*- coding: utf-8 -*-
"""Requisitos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZikrqOdX7lkAmIh0EImbc9SKEmO4AkLP
"""

requisitos = '''
streamlit
pandas
langchain
langchain-openai
langchain-experimental
'''

with open("requirements.txt", "w") as f:
    f.write(requisitos)